services:
  - type: web
    name: nexplay-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: BASE44_SERVICE_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        value: "1008276731024658492"
      - key: APP_ID
        value: "6a5226b5047f5c59d961130e"
    healthCheckPath: /
